spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017/topline"
cors:
  accessControlAllowOrigin: "*"
  accessControlMaxAge: "3600"
  accessControlAllowMethods: "POST, PUT, GET, OPTIONS, DELETE, PATCH"
  accessControlAllowHeaders: "Authorization Content-Type Accept Origin"
logging:
  level:
    org:
      springframework:
        web: INFO
        data:
          mongodb:
            core:
              MongoTemplate: INFO
oauth:
  google:
    scope: "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
    accessType: "offline"
    responseType: "code"
    clientId: "778566137835-4i6bsjd75h0pv4ciutli6dosgjhu4eo8.apps.googleusercontent.com"
    clientSecret: "dummy"
    redirectUrl: "https://localhost:4000/oauth/google/callback"
    profileUrl: "https://www.googleapis.com/userinfo/v2/me"
    tokenUrl: "https://oauth2.googleapis.com/token"
  linkedin:
    scope: "r_liteprofile r_emailaddress w_member_social"
    accessType: "offline"
    responseType: "code"
    clientId: "7818e4yxa1t0yn"
    clientSecret: "Dummy"
    redirectUrl: "http://localhost:9095/oauth/linkedin/callback"
    tokenUrl: "https://www.linkedin.com/oauth/v2/accessToken"
shiro:
  cachingEnabled: false
  authorizationCachingEnabled: false
  authenticationCachingEnabled: false
server:
  port: 9095
  contextPath: /api/
jwt:
  secret: 2FP8Wlc4ADlMdxti2jLRsF9IjBMQyYKsIVsBPIDgX_iXyPeHQzFmPmPpGts9OpDuaFxGCPpb9mD9xWpSEMcxInaB_DDZtYE7SncLNFUCrQR_XoGY_vp4II3ssuxUI7G0IfPebmllUSh8JcGBkPVh9Ksqa-vReoGmy6TnXcGT_K8nZfDdVoFs1am-EUnVhUYjC94BAOLKasDWxjlHdltALiIWdpyncCX5NCh8vjVXRPQeiADJiW13gUKs-d2o6c-V3y1ABAVnw52r5O50oWmpoJS1FqqvH7dqjs8OvejlYCZKKEkKOVVvUgx604Jm_6UKr4VxUJydLrXqKW0y1nFXqA
  ttl: 900000
  issuer: "Harness Inc"
systemUser: Harness